"""Publish the EMF reports to Confluence — clearly separated so nobody confuses
"already merged" with "forecast", or the main stream with GCP.

Pages (in the configured "exa" folder):
  * ``EMF — Landed (current build)``    — commits since the newest CalVer release.
  * ``EMF — Coming: <line>``  (one per release line) — the risk-weighted forecast
    for that line's upcoming release(s); main stream and GCP get their own page.

Reuses the Lustre publisher's storage-format helpers and cadence.
"""

from __future__ import annotations

from datetime import datetime

from . import emf
from .publish import _areas_line, _esc, _table, next_update_pt, now_pt
from .sources.confluence import Confluence, ConfluenceError


def _companion_note(cfg) -> str:
    """A footer listing the sibling EMF pages so a reader can tell them apart."""
    emfc = cfg.emf or {}
    conf = emfc.get("confluence") or {}
    tmpl = conf.get("coming_title_template", "EMF — Coming: {line_label}")
    parts = [f'<strong>{_esc(conf.get("landed_title", "EMF — Landed"))}</strong> (already merged)']
    for ln in (emfc.get("release_lines") or []):
        title = tmpl.format(line_label=ln.get("label"), line=ln.get("key"))
        note = ln.get("note") or ln.get("label")
        parts.append(f"<strong>{_esc(title)}</strong> ({_esc(note)})")
    return "<p><em>Companion EMF pages in this folder: " + " · ".join(parts) + ".</em></p>"


def _info(banner_html: str, now: datetime) -> str:
    ts, nxt = now.strftime("%Y-%m-%d %H:%M"), next_update_pt(now).strftime("%Y-%m-%d %H:%M")
    return ('<ac:structured-macro ac:name="info"><ac:rich-text-body>'
            f"<p><strong>Updated {ts} PT</strong> · next update {nxt} PT · "
            "auto-generated by EXA Reporter.</p>" + banner_html +
            "</ac:rich-text-body></ac:structured-macro>")


def build_landed_html(cfg, landed: dict, *, now: datetime | None = None) -> str:
    now = now or now_pt()
    emfc = cfg.emf or {}
    parts = [_info(
        f"<p><em>What this is:</em> commits merged onto <code>{_esc(landed.get('branch') or emfc.get('release_branch'))}</code> "
        f"(<code>{_esc(emfc.get('repo'))}</code>) <strong>since the newest CalVer release</strong> — "
        "i.e. what is queued for the next build. This is history, <strong>not</strong> a forecast.</p>", now)]
    if not landed.get("ok"):
        parts.append(f"<p><strong>Unavailable:</strong> {_esc(landed.get('error'))}</p>")
        parts.append(_companion_note(cfg))
        return "".join(parts)
    parts.append(f"<h2>Since {_esc(landed.get('tag'))} ({_esc(landed.get('tag_date'))}) — "
                 f"{landed.get('count', 0)} merged</h2>")
    parts.append(_areas_line(landed.get("areas")))
    parts.append(_table(cfg, landed.get("patches")))
    parts.append(_companion_note(cfg))
    return "".join(parts)


def _forecast_table(items: list[dict]) -> str:
    if not items:
        return "<p><em>No open items.</em></p>"
    head = ("<tr><th>Chance</th><th>Status</th><th>Ticket</th>"
            "<th>Summary</th><th>Assignee</th><th>PRs</th></tr>")
    rows = []
    for it in items:
        p = it.get("probability")
        chance = "—" if p is None else f"{round(p * 100)}%"
        prs = " ".join(
            f'<a href="{_esc(pr.get("url"))}">#{_esc(pr.get("number"))}</a>'
            for pr in (it.get("prs") or [])) or "—"
        rows.append(
            "<tr>"
            f"<td>{chance}</td>"
            f"<td>{_esc(it.get('status'))}</td>"
            f'<td><a href="{_esc(it.get("url"))}">{_esc(it.get("key"))}</a></td>'
            f"<td>{_esc(it.get('summary'))}</td>"
            f"<td>{_esc(it.get('assignee'))}</td>"
            f"<td>{prs}</td>"
            "</tr>")
    return f"<table><tbody>{head}{''.join(rows)}</tbody></table>"


def _when(days) -> str:
    if days is None:
        return "date TBD"
    if days < 0:
        return f"overdue by {abs(days)} days"
    return f"in {days} days"


def build_coming_html(cfg, line: dict, releases: list[dict], *, now: datetime | None = None) -> str:
    now = now or now_pt()
    label, note = line.get("label"), line.get("note")
    parts = [_info(
        f"<p><em>What this is:</em> a <strong>probabilistic forecast</strong> of what lands in the "
        f"upcoming <strong>{_esc(label)}</strong> release"
        + (f" — {_esc(note)}" if note else "") +
        ". Open EX Jira items are weighted by status and days-to-release. "
        "An estimate for planning, <strong>not</strong> a commitment.</p>", now)]
    for r in releases:
        parts.append(f"<h2>{_esc(r['name'])} — due {_esc(r.get('release_date') or 'no date')} "
                     f"({_esc(_when(r.get('days')))})</h2>")
        if not r.get("items_ok"):
            parts.append(f"<p><strong>Jira unavailable:</strong> {_esc(r.get('items_error'))}</p>")
            continue
        t = r.get("tiers") or {}

        def _c(k):
            return (t.get(k) or {}).get("count", 0)

        def _e(k):
            return (t.get(k) or {}).get("expected", 0)

        parts.append(f"<p><strong>Expected to land: ~{r.get('expected')} of "
                     f"{r.get('total')} open items.</strong></p>")
        line_summary = (f"In Review: {_c('review')} (~{_e('review')} land) · "
                        f"In Progress: {_c('progress')} (~{_e('progress')} land) · "
                        f"To Do: {_c('todo')} (~{_e('todo')} land)")
        if _c("other"):
            line_summary += f" · Other: {_c('other')}"
        parts.append(f"<p>{line_summary}</p>")
        parts.append(_forecast_table(r.get("items")))
    parts.append(_companion_note(cfg))
    return "".join(parts)


def publish_all(cfg) -> dict:
    """Upsert the EMF landed page + one coming page per release line."""
    emfc = cfg.emf or {}
    conf = emfc.get("confluence") or {}
    if not (emfc.get("enabled") and conf.get("enabled")):
        return {"ok": False, "error": "EMF Confluence publishing is disabled "
                "(emf.enabled + emf.confluence.enabled)."}
    if not conf.get("space_id"):
        return {"ok": False, "error": "emf.confluence.space_id not configured."}
    try:
        client = Confluence(conf.get("site"))
    except ConfluenceError as exc:
        return {"ok": False, "error": str(exc)}

    now = now_pt()
    space, parent = conf["space_id"], conf.get("parent_id")
    results = []

    landed_title = conf.get("landed_title", "EMF — Landed (current build)")
    try:
        up = client.upsert(space, parent, landed_title,
                           build_landed_html(cfg, emf.collect_landed(cfg), now=now))
        results.append({"page": "landed", "title": landed_title, "ok": True, **up})
    except ConfluenceError as exc:
        results.append({"page": "landed", "title": landed_title, "ok": False, "error": str(exc)})

    coming = emf.collect_coming(cfg)
    if not coming.get("ok"):
        results.append({"page": "coming", "ok": False, "error": coming.get("error")})
    else:
        by_line: dict = {}
        for r in coming["releases"]:
            by_line.setdefault(r.get("line", "other"), []).append(r)
        tmpl = conf.get("coming_title_template", "EMF — Coming: {line_label}")
        for ln in (emfc.get("release_lines") or []):
            rels = by_line.get(ln.get("key"))
            if not rels:
                continue                      # no upcoming release on this line — skip
            title = tmpl.format(line_label=ln.get("label"), line=ln.get("key"))
            try:
                up = client.upsert(space, parent, title, build_coming_html(cfg, ln, rels, now=now))
                results.append({"page": "coming:" + ln.get("key"), "title": title, "ok": True, **up})
            except ConfluenceError as exc:
                results.append({"page": "coming:" + ln.get("key"), "title": title,
                                "ok": False, "error": str(exc)})

    return {"ok": all(r.get("ok") for r in results) if results else False,
            "published_at": now.strftime("%Y-%m-%d %H:%M %Z"),
            "results": results}
